### ISSUE TITLE
[Backend] Definir modelagem de todas as entidades para o SGBD

### ISSUE THREAD

**Issue by DLRibeiro** [TeamWorkQualityReport/TeamWorkQualityReport#16]

**Comment by lhaisrs** [comment]
Visualização das entidades e modelos:
![entidades_models](https://user-images.githubusercontent.com/12106087/30547375-7aed3c66-9c65-11e7-90e6-ec146a7c5a8c.png)

Arquivo de edição no Astah Professional:
https://drive.google.com/a/cin.ufpe.br/file/d/0B7H7uMjVz4WscjFiUmR2OFFyd2M/view?usp=sharing
